version: '3'

services:

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    ports:
      - 8002:8002
    volumes:
      - ./django_labeller:/app
    networks:
      - irislocalapi_api-net

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
    logging:
      driver: none
    networks:
      - irislocalapi_api-net

  celery:
    build: .
    command: ['celery', '-A', 'example_labeller_app', 'worker', '-l', 'info']
    volumes:
      - ./django_labeller:/app
    networks:
      - irislocalapi_api-net
    depends_on:
      - rabbitmq

networks:
  irislocalapi_api-net:
    external: true
