# Generated by Django 3.2.6 on 2021-08-30 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_labeller', '0004_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotated_at', models.DateTimeField()),
                ('annotation_json', models.JSONField()),
                ('annotation_type', models.CharField(max_length=50)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_labeller.photo')),
            ],
        ),
    ]
