# Generated by Django 3.2.6 on 2021-09-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_labeller', '0006_auto_20210901_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewithlabels',
            name='height',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagewithlabels',
            name='width',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
