# Generated by Django 3.2.6 on 2021-09-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_labeller', '0007_auto_20210901_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagewithlabels',
            name='image',
        ),
    ]
