# Generated by Django 3.2.6 on 2021-09-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_labeller', '0008_remove_imagewithlabels_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewithlabels',
            name='foreign_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
