# Generated by Django 3.2.6 on 2021-09-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_labeller', '0009_imagewithlabels_foreign_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagewithlabels',
            name='foreign_id',
        ),
    ]
